BRE-921 fix: ci testing
minor spacing

fix attempt

```
KeyError: 'tag_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/bin/bwwl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/bitwarden_workflow_linter/cli.py", line 49, in main
    return actions_cmd.update(args.output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/bitwarden_workflow_linter/actions.py", line 228, in update
    latest_release = self.get_latest_version(action)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/bitwarden_workflow_linter/actions.py", line 168, in get_latest_version
    raise GitHubApiSchemaError(
bitwarden_workflow_linter.actions.GitHubApiSchemaError: Error with the GitHub API Response Schema for either /releases or/tags: 'tag_name'
Error: Process completed with exit code 1.
```